version: 2
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine:latest
    steps:
      - checkout
      - run:
          name: System information
          command: uname -a
      - run:
          name: ShellCheck version
          command: shellcheck --version
      - run:
          name: Run ShellCheck
          command: shellcheck --exclude=SC2016,SC2054,SC2191 ./*.sh
