version: 2
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: ShellCheck version
          command: shellcheck --version
      - run:
          name: Run ShellCheck
          command: shellcheck --exclude=SC2016,SC2209 -- ./*.sh
