version: 2.1

executors:
  gcc:
    parameters:
      version:
        type: string
    docker:
      - image: gcc:<< parameters.version >>

jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: ShellCheck version
          command: shellcheck --version
      - run:
          name: Run ShellCheck
          command: shellcheck --exclude=SC2016,SC2209 -- ./*.sh
  build:
    parameters:
      version:
        type: string
      file:
        type: string
    executor:
      name: gcc
      version: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Compiler version
          command: cc --version
      - run:
          name: << parameters.file >> (gcc:<< parameters.version >>)
          command: ./<< parameters.file >>

workflows:
  lints:
    jobs:
      - lint
      - build:
          requires:
            - lint
          matrix:
            parameters:
              version:
                - "10"
                - "9"
                - "8"
                - "7"
              file:
                - git_install.sh
                - libevent_install.sh
                - openssh_install.sh
                - ruby_install.sh
                - tmux_install.sh
                - vim_install.sh
